### ISSUE TITLE
elf 

### ISSUE THREAD

**Issue by vmcall** [can1357/ThePerfectInjector#7]
can this inject elf binaries into me?

**Comment by vmcall** [comment]
i thougght it was perfect

**Comment by vmcall** [comment]
adjective
/ˈpəːfɪkt/
1.
having all the required or desirable elements, qualities, or characteristics; as good as it is possible to be.
"life certainly isn't perfect at the moment"

**Comment by can1357** [comment]
ha

**Comment by can1357** [comment]
ha

**Comment by can1357** [comment]
ha

**Comment by can1357** [comment]
ha

**Comment by can1357** [comment]
ha

**Comment by can1357** [comment]
ha

**Comment by can1357** [comment]
ha

**Comment by can1357** [comment]
ha

**Comment by can1357** [comment]
hahaha

**Comment by can1357** [comment]
hahahahaa

**Comment by can1357** [comment]
hahahahahahaha

**Comment by marcussacana** [comment]
Issue 404

**Comment by vmcall** [comment]
amk orospu çocuğu
