### ISSUE TITLE
MEMORY_MANAGEMENT bsod because of PEPROCESS->AddressPolicy

### ISSUE THREAD

**Issue by estimated1337** [can1357/ThePerfectInjector#9]
i got MEMORY_MANAGEMENT bsod in MiCheckProcessShadow function, i assume that injector doesnt support KVAShadowing?
![bugcheck call code](https://i.imgur.com/AgsWYFf.png)
![bugcheck call code 2](https://i.imgur.com/nTEB9qn.png)
if i manually disable KVAShadowing then it works perfectly
and also if solution to fix that bsod is presumably simple i will be thankful for explanation

**Comment by hasikill** [comment]
I have the same problem, Have you solved this problem?

**Comment by estimated1337** [comment]
> I have the same problem, Have you solved this problem?

target process must be runned with admin privileges
